//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PepApp.rc

#define IDR_MANIFEST 1

#define IDI_PEPAPP 1

#define IDB_SPLASH 1

#define IDS_APPTITLE 1
#define IDS_CANNOTCREATEAPPWINDOW 2
#define IDS_CANNOTCREATEWORKERTHREAD 3
#define IDS_APPLICATIONALREADYRUNNING 4
#define IDS_UNSUPPORTEDWINDOWSVERSION 5
#define IDS_UNKNOWNERROR 6
#define IDS_COMMANDLINEHELP 8
#define IDS_PLUGINSLOADFAILED 9
