//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PepSetup.rc

#define RT_BINARY 100

#define IDR_MANIFEST 1

#define IDR_UTLISTPORTSDLL 1
#define IDR_PEPSETUPMSI 2
#define IDR_VCREDIST 3
#define IDR_NETFRAMEWORK4 4

#define IDI_PEPSETUP 1

#define IDD_PEPSETUP 1

#define IDC_STATUSLABEL 100
#define IDC_PROGRESSBAR 101

#define IDS_APPTITLE 1
#define IDS_CANNOTCREATEAPPWINDOW 2
#define IDS_CANNOTCREATEINSTALLTHREAD 3
#define IDS_APPLICATIONALREADYRUNNING 4
#define IDS_UNSUPPORTEDWINDOWSVERSION 5
#define IDS_UNKNOWNERROR 6
#define IDS_MSICOULDNOTBECOPIED 7
#define IDS_COMMANDLINEHELP 8
#define IDS_ANOTHERINSTALLATIONRUNNING 9
#define IDS_INSTALLATIONERROR 10
#define IDS_REBOOTREQUIRED 11
#define IDS_INSTALLINGFILES 12
#define IDS_CHECKINGVISUALSTUDIOREDIST 13
#define IDS_INSTALLINGVISUALSTUDIOREDIST 14
#define IDS_VISUALSTUDIOREDISTINSTALLED 15
#define IDS_EXTRACTINGSETUPFILES 16
#define IDS_CHECKINGNETFRAMEWORK 17
#define IDS_INSTALLINGNETFRAMEWORK 18
#define IDS_NETFRAMEWORKINSTALLED 19
#define IDS_REBOOTFAILED 20
#define IDS_UNINSTALL 21
#define IDS_UNINSTALLING 22
